//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruzChelb.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChelGruzEntities : DbContext
    {
        private static ChelGruzEntities Context;
        public ChelGruzEntities()
            : base("name=ChelGruzEntities")
        {
        }

        public static ChelGruzEntities GetContext()
        {
            if (Context == null)
                Context = new ChelGruzEntities();
            return Context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ProdInOrders> ProdInOrders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
