//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruzChelb.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProdInOrders = new HashSet<ProdInOrders>();
        }
    
        public int Id { get; set; }
        public int NumWorker { get; set; }
        public int NumClient { get; set; }
        public int NumRate { get; set; }
        public string AddressDelivery { get; set; }
        public double DistanceKm { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rates Rates { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdInOrders> ProdInOrders { get; set; }
    }
}
